services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:3000
      ConnectionStrings__DefaultConnection: "Data Source=/data/footballclub.db"
    volumes:
      - ./.stack-data/db:/data
    cpus: 0.5
    mem_limit: 512m
